### PR TITLE
Add support for downloading s3:// URLs using Boto across all pipelines

### PR DESCRIPTION
**Pull request by hannes-ucsc**
plus cosmetics

rebased version of https://github.com/BD2KGenomics/toil-scripts/pull/119

### CODE REVIEW

**Comment by hannes-ucsc** [comment]
Just in case you need it. You can merge this and we'll abandon https://github.com/BD2KGenomics/toil-scripts/pull/119.

**Comment by fnothaft** [comment]
Thanks @hannes-ucsc! So far, this looks good. We're running through HaplotypeCaller right now. I'll rerun my tests with this rebased branch shortly to check.

BTW, can you look at cgcloud jenkins? Uploads from the [last cgl-docker-lib build](http://jenkins.cgcloud.info/job/cgl-docker-lib/104) seem to be failing due to disk space errors:

```
docker build -t quay.io/ucsc_cgl/kallisto:0.42.4--256539928ea162949d8a65ca5c79a72ef557ce7c .
unable to process Dockerfile: write /tmp/trusted-dockerfile-407312363: no space left on device
make: *** [build] Error 1
docker build -t quay.io/ucsc_cgl/genetorrent:3.8.7--256539928ea162949d8a65ca5c79a72ef557ce7c .
unable to process Dockerfile: write /tmp/trusted-dockerfile-230813357: no space left on device
make: *** [build] Error 1
make: Nothing to be done for `test'.
python test.py
F
======================================================================
FAIL: test_docker_call (__main__.TestADAM)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 12, in test_docker_call
    self.assertTrue('ADAM_MAIN=org.bdgenomics.adam.cli.ADAMMain' in out)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 1 test in 2.869s

FAILED (failures=1)
```

**Comment by hannes-ucsc** [comment]
Switched TMPDIR, upped instance-type and restarted build. Looking at why build wasn't failing with these obvious failures.

**Comment by fnothaft** [comment]
> Switched TMPDIR, upped instance-type and restarted build. Looking at why build wasn't failing with these obvious failures.

Thanks for following up! Looks like this build is going much more smoothly...

**Comment by fnothaft** [comment]
I have merged this locally and am testing now.

**Comment by fnothaft** [comment]
Merged manually. Thanks @hannes-ucsc!

**Pull request closed without merging**
